/**
 * scripts/skill-autoload-audit/deprecation-notice.ts
 *
 * When a skill's autoload trigger classification changes (e.g., from
 * model-invoked → user-invoked after classify.ts recommends
 * `disable-model-invocation: true`), this module emits a one-time advisory
 * entry to the loom-doctor advisory file.
 *
 * Each advisory entry is deduplicated by skill name so re-running the
 * audit does not produce duplicate notices.
 *
 * Advisory file location (per loom-doctor protocol):
 *   .plan-execution/reports/skill-autoload-advisories.toon
 *
 * Usage (called programmatically from classify.ts or standalone):
 *   bunx tsx scripts/skill-autoload-audit/deprecation-notice.ts \
 *     --skill <name> \
 *     --prior-trigger "model-invoked via description" \
 *     --new-invocation-path "/loom-<name>" \
 *     [--advisory-file <path>]
 *
 * Advisory format (TOON):
 *   entries[N]{skillName,priorTrigger,newInvocationPath,emittedAt}:
 *     shell-conventions,"model-invoked via description","/loom-shell-conventions",2026-06-26T00:00:00Z
 */

import {
  readFileSync,
  writeFileSync,
  renameSync,
  mkdirSync,
  existsSync,
} from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..", "..");

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AdvisoryEntry {
  skillName: string;
  priorTrigger: string;
  newInvocationPath: string;
  emittedAt: string;
}

// ---------------------------------------------------------------------------
// Advisory file parsing
// ---------------------------------------------------------------------------

const HEADER_LINES_PREFIX = "entries[";

/**
 * Parse existing advisory entries from a TOON file.
 * Returns an empty array if the file doesn't exist or is unparseable.
 */
function readAdvisories(filePath: string): AdvisoryEntry[] {
  if (!existsSync(filePath)) return [];

  let content: string;
  try {
    content = readFileSync(filePath, "utf8");
  } catch {
    return [];
  }

  const entries: AdvisoryEntry[] = [];
  let inTable = false;

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith(HEADER_LINES_PREFIX)) {
      inTable = true;
      continue;
    }
    if (inTable && trimmed.length > 0 && !trimmed.startsWith("#")) {
      // Row: skillName,"priorTrigger","newInvocationPath",emittedAt
      const parts = parseCSVRow(trimmed);
      if (parts.length >= 4) {
        entries.push({
          skillName: parts[0],
          priorTrigger: parts[1],
          newInvocationPath: parts[2],
          emittedAt: parts[3],
        });
      }
    }
  }

  return entries;
}

/**
 * Very minimal CSV row parser (handles double-quoted fields with no embedded newlines).
 */
function parseCSVRow(row: string): string[] {
  const parts: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < row.length; i++) {
    const ch = row[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === "," && !inQuotes) {
      parts.push(current.trim());
      current = "";
    } else {
      current += ch;
    }
  }
  parts.push(current.trim());
  return parts;
}

// ---------------------------------------------------------------------------
// Advisory file serialisation
// ---------------------------------------------------------------------------

function serialiseAdvisories(entries: AdvisoryEntry[]): string {
  const rowLines = entries
    .map(
      (e) =>
        `  ${e.skillName},"${e.priorTrigger}","${e.newInvocationPath}",${e.emittedAt}`,
    )
    .join("\n");

  return [
    `# loom-doctor skill-autoload advisory notices`,
    `# Generated by scripts/skill-autoload-audit/deprecation-notice.ts`,
    `# Each entry is deduplicated by skillName.`,
    ``,
    `entries[${entries.length}]{skillName,priorTrigger,newInvocationPath,emittedAt}:`,
    rowLines,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Emit a one-time advisory notice for a skill whose autoload trigger changed.
 * Deduplicates by skillName — existing entries for the same skill are replaced.
 *
 * @param skillName     The skill identifier (e.g. "shell-conventions").
 * @param priorTrigger  Description of the previous trigger (e.g. "model-invoked via description").
 * @param newInvocationPath  The new way users invoke the skill (e.g. "/loom-shell-conventions").
 * @param advisoryFilePath   Path to the advisory TOON file (defaults to standard path).
 * @returns The final path where the advisory was written.
 */
export function emitDeprecationNotice(
  skillName: string,
  priorTrigger: string,
  newInvocationPath: string,
  advisoryFilePath?: string,
): string {
  const filePath =
    advisoryFilePath ??
    join(
      REPO_ROOT,
      ".plan-execution",
      "reports",
      "skill-autoload-advisories.toon",
    );

  const existing = readAdvisories(filePath);

  // Deduplicate: replace existing entry for this skill
  const filtered = existing.filter((e) => e.skillName !== skillName);
  const newEntry: AdvisoryEntry = {
    skillName,
    priorTrigger,
    newInvocationPath,
    emittedAt: new Date().toISOString(),
  };
  const updated = [...filtered, newEntry];

  mkdirSync(dirname(filePath), { recursive: true });
  const tmpPath = filePath + ".tmp";
  writeFileSync(tmpPath, serialiseAdvisories(updated), "utf8");
  renameSync(tmpPath, filePath);

  return filePath;
}

// ---------------------------------------------------------------------------
// CLI entrypoint
// ---------------------------------------------------------------------------

function main(): void {
  const args = process.argv.slice(2);

  let skillName = "";
  let priorTrigger = "";
  let newInvocationPath = "";
  let advisoryFile: string | undefined;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--skill" && args[i + 1]) {
      skillName = args[++i];
    } else if (args[i] === "--prior-trigger" && args[i + 1]) {
      priorTrigger = args[++i];
    } else if (args[i] === "--new-invocation-path" && args[i + 1]) {
      newInvocationPath = args[++i];
    } else if (args[i] === "--advisory-file" && args[i + 1]) {
      advisoryFile = args[++i];
    }
  }

  if (!skillName || !priorTrigger || !newInvocationPath) {
    console.error(
      "Usage: deprecation-notice.ts --skill <name> --prior-trigger <text> --new-invocation-path <path> [--advisory-file <path>]",
    );
    process.exit(1);
  }

  const written = emitDeprecationNotice(
    skillName,
    priorTrigger,
    newInvocationPath,
    advisoryFile,
  );
  console.log(`[deprecation-notice] Advisory written to: ${written}`);
  console.log(
    `  Skill: ${skillName} | Prior: ${priorTrigger} | New path: ${newInvocationPath}`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
