/**
 * tests/commands/loom-note-triage.test.ts
 *
 * Tests for the loom-note triage state machine integration in commands/loom-note.md.
 *
 * Validates that:
 * - commands/loom-note.md contains the triage inbox instructions
 * - Every documented transition is described
 * - Every undocumented transition has a documented error code
 * - AI disclaimer prefix is documented
 * - /loom-note reopen requires --reason
 * - transitions[] append-only audit log is documented
 * - createdAt, updatedAt fields are documented
 *
 * Run: bunx vitest run tests/commands/loom-note-triage.test.ts
 */

import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve, join } from "node:path";

const REPO_ROOT = resolve(__dirname, "../..");
const LOOM_NOTE_PATH = join(REPO_ROOT, "commands/loom-note.md");

let content: string;

beforeAll(() => {
  content = readFileSync(LOOM_NOTE_PATH, "utf8");
});

// ── File existence ────────────────────────────────────────────────────────────

describe("commands/loom-note.md — triage integration", () => {
  it("commands/loom-note.md exists", () => {
    expect(existsSync(LOOM_NOTE_PATH)).toBe(true);
  });

  // ── Inbox fields ─────────────────────────────────────────────────────────

  describe("inbox entry fields", () => {
    it("documents createdAt field", () => {
      expect(content).toContain("createdAt");
    });

    it("documents updatedAt field", () => {
      expect(content).toContain("updatedAt");
    });

    it("documents transitions[] field", () => {
      expect(content).toMatch(/transitions\[/);
    });

    it("documents append-only transitions audit log", () => {
      expect(content).toMatch(/append-only/i);
    });
  });

  // ── Valid transitions documented ─────────────────────────────────────────

  describe("documented valid transitions", () => {
    it("documents needs-triage → needs-info", () => {
      expect(content).toContain("needs-triage");
      expect(content).toContain("needs-info");
    });

    it("documents needs-triage → ready-for-agent", () => {
      expect(content).toContain("ready-for-agent");
    });

    it("documents needs-triage → ready-for-human", () => {
      expect(content).toContain("ready-for-human");
    });

    it("documents needs-triage → wontfix", () => {
      expect(content).toContain("wontfix");
    });

    it("documents needs-info → needs-triage (reporter activity)", () => {
      // Both states referenced
      expect(content).toContain("needs-info");
      expect(content).toContain("needs-triage");
    });

    it("documents needs-info → wontfix", () => {
      expect(content).toContain("needs-info");
      expect(content).toContain("wontfix");
    });

    it("documents all 5 triage states", () => {
      const states = ["needs-triage", "needs-info", "ready-for-agent", "ready-for-human", "wontfix"];
      for (const state of states) {
        expect(content).toContain(state);
      }
    });
  });

  // ── Error codes ────────────────────────────────────────────────────────────

  describe("error codes for undocumented transitions", () => {
    it("documents INVALID_TRANSITION error code", () => {
      expect(content).toContain("INVALID_TRANSITION");
    });

    it("documents WONTFIX_REOPEN_REQUIRED error code", () => {
      expect(content).toContain("WONTFIX_REOPEN_REQUIRED");
    });
  });

  // ── AI disclaimer prefix ──────────────────────────────────────────────────

  describe("AI disclaimer prefix for bot-posted comments", () => {
    it("documents the verbatim AI disclaimer prefix", () => {
      expect(content).toContain("> *This was generated by AI during triage.*");
    });

    it("states the prefix is required on every bot-posted comment", () => {
      // The instructions should reference bot-posted comments needing the prefix
      expect(content).toMatch(/bot.posted|AI.generated|generated by AI/i);
    });
  });

  // ── /loom-note reopen ─────────────────────────────────────────────────────

  describe("/loom-note reopen requires --reason", () => {
    it("documents the reopen subcommand", () => {
      expect(content).toMatch(/reopen/i);
    });

    it("documents that --reason is mandatory on reopen", () => {
      expect(content).toMatch(/--reason.*(mandatory|required)|mandatory.*--reason/i);
    });

    it("documents that reopen appends a transitions[] row with actor and reason", () => {
      expect(content).toMatch(/actor/);
      expect(content).toMatch(/reason/);
    });
  });

  // ── State machine reference ───────────────────────────────────────────────

  describe("state machine reference", () => {
    it("references scripts/triage/state-machine.ts", () => {
      expect(content).toContain("scripts/triage/state-machine");
    });
  });
});

// ── Functional tests using state-machine.ts directly ─────────────────────────

import {
  transition,
  type TriageEntry,
  type TriageStateValue,
} from "../../scripts/triage/state-machine.js";

function makeEntry(state: TriageStateValue = "needs-triage"): TriageEntry {
  return {
    id: "NOTE-001",
    category: "enhancement",
    state,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    transitions: [],
  };
}

describe("state machine — all documented transitions succeed", () => {
  const validCases: Array<[TriageStateValue, TriageStateValue, string?]> = [
    ["needs-triage", "needs-info", undefined],
    ["needs-triage", "ready-for-agent", undefined],
    ["needs-triage", "ready-for-human", undefined],
    ["needs-triage", "wontfix", "explicit decision"],
    ["needs-info", "needs-triage", undefined],
    ["needs-info", "wontfix", "timeout-30d"],
    ["ready-for-agent", "ready-for-human", undefined],
    ["ready-for-human", "ready-for-agent", undefined],
  ];

  for (const [from, to, reason] of validCases) {
    it(`${from} → ${to} succeeds`, () => {
      const entry = makeEntry(from);
      const opts = reason
        ? { actor: "agent" as const, reason }
        : { actor: "agent" as const };
      const result = transition(entry, to, opts);
      expect(result.ok).toBe(true);
    });
  }

  it("wontfix → needs-triage succeeds with explicitReopen + reason", () => {
    const entry = makeEntry("wontfix");
    const result = transition(entry, "needs-triage", {
      actor: "human",
      reason: "new evidence",
      explicitReopen: true,
    });
    expect(result.ok).toBe(true);
  });
});

describe("state machine — undocumented transitions exit with documented error codes", () => {
  it("ready-for-agent → needs-triage returns INVALID_TRANSITION", () => {
    const entry = makeEntry("ready-for-agent");
    const result = transition(entry, "needs-triage", { actor: "agent" });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.errorCode).toBe("INVALID_TRANSITION");
  });

  it("wontfix → needs-triage without reopen returns WONTFIX_REOPEN_REQUIRED", () => {
    const entry = makeEntry("wontfix");
    const result = transition(entry, "needs-triage", { actor: "agent" });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.errorCode).toBe("WONTFIX_REOPEN_REQUIRED");
  });

  it("ready-for-human → needs-triage returns INVALID_TRANSITION", () => {
    const entry = makeEntry("ready-for-human");
    const result = transition(entry, "needs-triage", { actor: "agent" });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.errorCode).toBe("INVALID_TRANSITION");
  });
});
