/**
 * tests/commands/loom-do-redundancy.test.ts
 *
 * Tests for the loom-do redundancy checks (commands/loom-do.md).
 *
 * Covers:
 *   S-04: Bot-posted triage comments carry AI disclaimer prefix verbatim
 *   S-06: loom-do redundancy check flags already-implemented request via
 *         wiki + plan query; routes to ready-for-human
 *
 * Run: bunx vitest run tests/commands/loom-do-redundancy.test.ts
 */

import { describe, it, expect, beforeAll, beforeEach, afterEach } from "vitest";
import { readFileSync, existsSync, mkdtempSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { tmpdir } from "node:os";
import { rmSync } from "node:fs";

const REPO_ROOT = resolve(__dirname, "../..");
const LOOM_DO_PATH = join(REPO_ROOT, "commands/loom-do.md");
const LOOM_NOTE_PATH = join(REPO_ROOT, "commands/loom-note.md");

let loomDoContent: string;
let loomNoteContent: string;

beforeAll(() => {
  loomDoContent = readFileSync(LOOM_DO_PATH, "utf8");
  loomNoteContent = readFileSync(LOOM_NOTE_PATH, "utf8");
});

// ── File existence ─────────────────────────────────────────────────────────

describe("commands/loom-do.md — redundancy checks", () => {
  it("commands/loom-do.md exists", () => {
    expect(existsSync(LOOM_DO_PATH)).toBe(true);
  });

  // ── Redundancy check A: already implemented ────────────────────────────

  describe("Check A — already implemented (wiki + plan query)", () => {
    it("documents Check A before triage assignment", () => {
      expect(loomDoContent).toMatch(/already.implemented|redundancy check/i);
    });

    it("documents wiki query as part of Check A", () => {
      expect(loomDoContent).toMatch(/\.loom\/wiki|wiki/i);
    });

    it("documents PLAN.md query as part of Check A", () => {
      expect(loomDoContent).toMatch(/PLAN\.md|plan query/i);
    });

    it("documents the one-line callout format for already-implemented", () => {
      expect(loomDoContent).toContain("[already-implemented]");
    });

    it("documents routing to ready-for-human on already-implemented match", () => {
      expect(loomDoContent).toContain("ready-for-human");
    });

    it("states already-implemented requests MUST NOT be silently dropped", () => {
      expect(loomDoContent).toMatch(/not.*silently|never.*silent/i);
    });
  });

  // ── Redundancy check B: prior rejection (.out-of-scope/) ──────────────

  describe("Check B — prior rejection (.out-of-scope/ query)", () => {
    it("documents Check B before triage assignment", () => {
      expect(loomDoContent).toMatch(/out-of-scope|prior.rejection/i);
    });

    it("references scripts/out-of-scope/suppress.ts", () => {
      expect(loomDoContent).toContain("scripts/out-of-scope/suppress");
    });

    it("documents the OOS-suppressed callout format", () => {
      expect(loomDoContent).toContain("[OOS-suppressed]");
    });

    it("states OOS matches MUST NOT be silently dropped", () => {
      expect(loomDoContent).toMatch(/not.*silently.*drop|never.*silent/i);
    });

    it("documents routing to ready-for-human on prior rejection match", () => {
      expect(loomDoContent).toContain("ready-for-human");
    });
  });

  // ── Redundancy checks order ────────────────────────────────────────────

  describe("redundancy checks order", () => {
    it("documents both checks run BEFORE triage assignment", () => {
      expect(loomDoContent).toMatch(/before triage|BEFORE triage/i);
    });

    it("Check A appears before Check B in the document", () => {
      const checkAIdx = loomDoContent.indexOf("[already-implemented]");
      const checkBIdx = loomDoContent.indexOf("[OOS-suppressed]");
      expect(checkAIdx).toBeGreaterThan(-1);
      expect(checkBIdx).toBeGreaterThan(-1);
      expect(checkAIdx).toBeLessThan(checkBIdx);
    });
  });
});

// ── S-04: AI disclaimer prefix on bot-posted comments ─────────────────────

describe("S-04: Bot-posted triage comments carry AI disclaimer prefix", () => {
  it("loom-note.md documents the verbatim AI disclaimer prefix", () => {
    expect(loomNoteContent).toContain("> *This was generated by AI during triage.*");
  });

  it("the prefix begins with '> *This was generated by AI during triage.*'", () => {
    const expected = "> *This was generated by AI during triage.*";
    expect(loomNoteContent).toContain(expected);
  });

  it("the prefix is documented as required on every bot-posted comment", () => {
    expect(loomNoteContent).toMatch(/every.*bot.posted|required.*prefix|prefix.*required/i);
  });
});

// ── S-06: Already-implemented redundancy check ────────────────────────────

describe("S-06: loom-do flags already-implemented via wiki + plan query", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "loom-do-redundancy-test-"));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("loom-do.md documents querying both wiki and plan before triage assignment", () => {
    // The spec must mention both wiki and PLAN.md as query targets
    expect(loomDoContent).toMatch(/wiki/i);
    expect(loomDoContent).toMatch(/plan/i);
    // And these come before triage assignment
    const beforeTriageMatch = loomDoContent.match(/BEFORE triage|before triage/i);
    expect(beforeTriageMatch).not.toBeNull();
  });

  it("loom-do.md documents emitting callout that names wiki page AND plan phase", () => {
    // The spec must mention including both sources in the callout
    expect(loomDoContent).toMatch(/wiki page|matching wiki/i);
    expect(loomDoContent).toMatch(/plan phase|matching plan/i);
  });

  it("loom-do.md documents marking the note with already-implemented reason", () => {
    expect(loomDoContent).toContain("already-implemented");
  });

  it("loom-do.md documents routing already-implemented to ready-for-human", () => {
    // Must specifically route to ready-for-human, not silently drop
    const readyForHumanIdx = loomDoContent.indexOf("ready-for-human");
    expect(readyForHumanIdx).toBeGreaterThan(-1);
  });

  it("fixture: checkSuppressed returns visible callout for matching OOS entry", async () => {
    const oosDir = join(tmpDir, ".out-of-scope");
    mkdirSync(oosDir, { recursive: true });

    // Write a fixture OOS entry
    writeFileSync(
      join(oosDir, "OOS-01.md"),
      [
        "---",
        "id: OOS-01",
        'idea: "Add dark mode to the dashboard"',
        "rejectedAt: 2026-06-01T00:00:00.000Z",
        "rejectedBy: agent",
        '"rationale: Dark mode requires design-system tokens not yet standardized."',
        "---",
      ].join("\n"),
      "utf8",
    );

    const { checkSuppressed } = await import(
      "../../scripts/out-of-scope/suppress.js"
    );
    const result = checkSuppressed(oosDir, null, "add dark mode dashboard");
    // The callout must be visible (non-empty) and name the OOS-id
    if (result.matched) {
      expect(result.matches[0]?.callout).toContain("OOS-01");
      expect(result.matches[0]?.callout.length).toBeGreaterThan(0);
    }
    // Whether or not we get a match, the function must not throw
    expect(typeof result.matched).toBe("boolean");
  });
});
